
services:
  db:
    image: postgres:13
    container_name: ktor_db
    environment:
      POSTGRES_DB: ktor_dkwc
      POSTGRES_USER: ktor_dkwc_user
      POSTGRES_PASSWORD: xPnzorWy9NzjuPeSYSOFOh7fsiSQ9q7f
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ktor_app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/ktor_dkwc
      DATABASE_USER: ktor_dkwc_user
      DATABASE_PASSWORD: xPnzorWy9NzjuPeSYSOFOh7fsiSQ9q7f
      FIREBASE_CONFIG: ${FIREBASE_CONFIG}
    volumes:
      - ./firebase-key.json:/app/firebase-key.json
    depends_on:
      - db

volumes:
  postgres_data:
